from aiowialon.types import AvlEventCallback, AvlEventFilter, ClientLoginCallback, ClientLoginParams, ClientLogoutCallback, MultipartField, flags
from aiowialon.types.api_types import core, item, user, messages, unit_group, retranslator, token as token_params, other
from typing_extensions import Unpack, Any, Callable, Coroutine, Literal

__all__ = ['Wialon']

class Wialon:
    def __init__(self, scheme: Literal['https', 'http'] = 'https', host: str = 'hst-api.wialon.com', port: int | None = None, token: str | None = None, rps: int = 10) -> None: ...
    @property
    def token(self) -> str | None: ...
    @token.setter
    def token(self, token: str) -> None: ...
    @property
    def timeout(self) -> float: ...
    @timeout.setter
    def timeout(self, timeout: float) -> None: ...
    @property
    def session_lock(self) -> Callable: ...
    def on_session_open(self, callback: ClientLoginCallback | None = None) -> ClientLoginCallback | None: ...
    def on_session_close(self, callback: ClientLogoutCallback | None = None) -> ClientLogoutCallback | None: ...
    def avl_event_handler(self, filter_: AvlEventFilter | None = None) -> Callable: ...
    def avl_event_once(self, func: Callable[..., Coroutine[Any, Any, Any]] | None = None) -> Callable[..., Coroutine[Any, Any, Any]]: ...
    def remove_avl_event_handler(self, callback: str | AvlEventCallback): ...
    async def start_polling(self, timeout: int | float = 2, logout_finally: bool = True, **params: Unpack[ClientLoginParams]) -> None: ...
    async def stop_polling(self, logout: bool = False) -> None: ...
    async def login(self, **params: Unpack[ClientLoginParams]) -> token_params.TokenLoginResponse: ...
    async def logout(self) -> core.CoreErrorCode: ...
    async def avl_evts(self) -> other.AvlEventResponse: ...
    async def call(self, action_name: str, *args: Any, **params: Any) -> Any: ...
    async def batch(self, *calls: Coroutine[Any, Any, Any], flags_: flags.BatchFlag = ...) -> core.CoreBatchResponse: ...
    async def multipart(self, call: Coroutine[Any, Any, Any], *fields: MultipartField) -> Any: ...
    def __getattr__(self, action_name: str) -> Any: ...
    async def request(self, action_name: str, url: str, payload: Any) -> Any: ...
    async def wait(self, call: Coroutine[Any, Any, Any], timeout: float | None = None) -> Any: ...
    @staticmethod
    def help(service_name: str, action_name: str) -> None: ...

    """
    There are enumerated methods allowed via Wialon.<method> syntax in section bellow
    """
    """
    References to core service
    https://sdk.wialon.com/wiki/en/sidebar/remoteapi/apiref/core/core
    """
    async def core_logout(self) -> core.CoreErrorCode: ...
    async def core_get_account_data(self, **params: Unpack[core.CoreGetAccountDataParams]) -> core.CoreGetAccountDataResponse: ...
    async def core_check_items_billing(self, **params: Unpack[core.CoreChechItemsBillingParams]) -> core.CoreChechItemsBillingResponse: ...
    async def core_check_accessors(self, **params: Unpack[core.CoreCheckAccessorsParams]) -> core.CoreCheckAccessorsResponse: ...
    async def core_create_user(self, **params: Unpack[core.CoreCreateUserParams]) -> core.CoreCreateUserResponse: ...
    async def core_create_resource(self, **params: Unpack[core.CoreCreateResourceParams]) -> core.CoreCreateResourceResponse: ...
    async def core_create_unit(self, **params: Unpack[core.CoreCreateUnitParams]) -> core.CoreCreateUnitResponse: ...
    async def core_create_unit_group(self, **params: Unpack[core.CoreCreateUnitGroupParams]) -> core.CoreCreateUnitGroupResponse: ...
    async def core_create_retranslator(self, **params: Unpack[core.CoreCreateRetranslatorParams]) -> core.CoreCreateRetranslatorResponse: ...
    async def core_create_route(self, **params: Unpack[core.CoreCreateRouteParams]) -> core.CoreCreateRouteResponse: ...
    async def core_search_item(self, **params: Unpack[core.CoreSearchItemParams]) -> core.CoreSearchItemResponse: ...
    async def core_search_items(self, **params: Unpack[core.CoreSearchItemsParams]) -> core.CoreSearchItemsResponse: ...
    async def core_update_data_flags(self, **params: Unpack[core.CoreUpdateDataFlagsParams]) -> core.CoreUpdateDataFlagsResponse: ...
    async def core_get_hw_types(self, **params: Unpack[core.CoreGetHwTypesParams]) -> core.CoreGetHwTypesResponse: ...
    async def core_get_hw_cmds(self, **params: Unpack[core.CoreGetHwCommandsParams]) -> core.CoreGetHwCommandsTemplates: ...
    async def core_reset_password_request(self, **params: Unpack[core.CoreResetPasswordRequestParams]) -> core.CoreErrorCode: ...
    async def core_reset_password_perform(self, **params: Unpack[core.CoreResetPasswordPerformParams]) -> core.CoreResetPasswordPerformResponse: ...
    async def core_batch(self, **params: Unpack[core.CoreBatchParams]) -> core.CoreBatchResponse: ...
    async def core_duplicate(self, **params: Unpack[core.CoreDuplicateParams]) -> core.CoreDuplicateResponse: ...
    async def core_create_auth_hash(self) -> core.CoreCreateAuthHashResponse: ...
    async def core_use_auth_hash(self, **params: Unpack[core.CoreUseAuthHashParams]) -> core.CoreUseAuthHashResponse: ...
    async def core_check_unique(self, **params: Unpack[core.CoreCheckUniqueParams]) -> core.CoreCheckUniqueResponse: ...
    async def core_export_file(self, **params: Unpack[core.CoreExportFileParams]) -> core.CoreExportFileResponse: ...
    async def core_set_session_property(self, **params: Unpack[core.CoreSessionPropertyParams]) -> core.CoreSessionPropertyResponse: ...

    """
    References to item service
    https://sdk.wialon.com/wiki/en/sidebar/remoteapi/apiref/item/item
    """
    async def item_update_name(self, **params: Unpack[item.ItemUpdateNameParams]) -> item.ItemUpdateNameResponse: ...
    async def item_delete_item(self, **params: Unpack[item.ItemDeleteItemParams]) -> item.ItemDeleteItemResponse: ...
    async def item_update_custom_field(self, **params: Unpack[item.ItemUpdateCustomFieldParams]) -> item.ItemUpdateCustomFieldResponse: ...
    async def item_update_custom_property(self, **params: Unpack[item.ItemUpdateCustomPropertyParams]) -> item.ItemUpdateCustomPropertyResponse: ...
    async def item_update_admin_field(self, **params: Unpack[item.ItemUpdateAdminFieldParams]) -> item.ItemUpdateAdminFieldResponse: ...
    async def item_add_log_record(self, **params: Unpack[item.AddLogRecordParams]) -> item.AddLogRecordResponse: ...
    async def item_list_backups(self, **params: Unpack[item.ItemListBackupsParams]) -> item.ItemListBackupsResponse: ...
    async def item_update_measure_units(self, **params: Unpack[item.ItemUpdateMeasureUnitsParams]) -> item.ItemUpdateMeasureUnitsResponse: ...
    async def item_update_ftp_property(self, **params: Unpack[item.ItemUpdateFtpPropertyParams]) -> item.ItemUpdateFtpPropertyResponse: ...
    async def item_update_profile_field(self, **params: Unpack[item.ItemUpdateProfileFieldParams]) -> item.ItemUpdateProfileFieldResponse: ...
    async def item_restore_icons(self, **params: Unpack[item.ItemRestoreIconsParams]) -> item.ItemRestoreIconsResponse: ...

    """
    References to user service
    https://sdk.wialon.com/wiki/en/sidebar/remoteapi/apiref/user/user
    """
    async def user_verify_auth(self, **params: Unpack[user.UserVerifyAuthParams]) -> user.UserVerifyAuthResponse: ...
    async def user_update_auth_params(self, **params: Unpack[user.UserUpdateAuthParamsParams]) -> user.UserUpdateAuthParamsResponse: ...
    async def user_update_item_access(self, **params: Unpack[user.UserUpdateItemAccessParams]) -> user.UserUpdateItemAccessResponse: ...
    async def user_get_items_access(self, **params: Unpack[user.UserGetItemsAccessParams]) -> user.UserGetItemsAccessResponse: ...
    async def user_update_hosts_mask(self, **params: Unpack[user.UserUpdateHostsMaskParams]) -> user.UserUpdateHostsMaskResponse: ...
    async def user_update_user_notification(self, **params: Unpack[user.UserUpdateUserNotificationParams]) -> user.UserUpdateUserNotificationResponse: ...
    async def user_update_password(self, **params: Unpack[user.UserUpdatePasswordParams]) -> user.UserUpdatePasswordResponse: ...
    async def user_send_sms(self, **params: Unpack[user.UserSendSmsParams]) -> user.UserSendSmsResponse: ...
    async def user_update_user_flags(self, **params: Unpack[user.UserUpdateUserFlagsParams]) -> user.UserUpdateUserFlagsResponse: ...
    async def user_update_locale(self, **params: Unpack[user.UserUpdateLocaleParams]) -> user.UserUpdateLocaleResponse: ...
    async def user_get_locale(self, **params: Unpack[user.UserGetLocaleParams]) -> user.UserGetLocaleResponse: ...
    async def user_get_dst_time(self, **params: Unpack[user.UserGetDstTimeParams]) -> user.UserGetDstTimeResponse: ...

    """
    References to resource service
    https://sdk.wialon.com/wiki/en/sidebar/remoteapi/apiref/resource/resource
    """
    async def resource_get_zone_data(self, *args: Any, **params: Any) -> Any: ...
    async def resource_update_zone(self, *args: Any, **params: Any) -> Any: ...
    async def resource_create_zone_by_track(self, *args: Any, **params: Any) -> Any: ...
    async def resource_get_zones_by_point(self, *args: Any, **params: Any) -> Any: ...
    async def resource_upload_zone_image(self, *args: Any, **params: Any) -> Any: ...
    async def resource_update_zones_group(self, *args: Any, **params: Any) -> Any: ...
    async def resource_get_job_data(self, *args: Any, **params: Any) -> Any: ...
    async def resource_update_job(self, *args: Any, **params: Any) -> Any: ...
    async def resource_get_notification_data(self, *args: Any, **params: Any) -> Any: ...
    async def resource_update_notification(self, *args: Any, **params: Any) -> Any: ...
    async def resource_update_driver(self, *args: Any, **params: Any) -> Any: ...
    async def resource_upload_driver_image(self, *args: Any, **params: Any) -> Any: ...
    async def resource_bind_unit_driver(self, *args: Any, **params: Any) -> Any: ...
    async def resource_update_driver_units(self, *args: Any, **params: Any) -> Any: ...
    async def resource_get_driver_bindings(self, *args: Any, **params: Any) -> Any: ...
    async def resource_get_unit_drivers(self, *args: Any, **params: Any) -> Any: ...
    async def resource_cleanup_driver_interval(self, *args: Any, **params: Any) -> Any: ...
    async def resource_upload_tacho_file(self, *args: Any, **params: Any) -> Any: ...
    async def resource_driver_operate(self, *args: Any, **params: Any) -> Any: ...
    async def resource_driver_status(self, *args: Any, **params: Any) -> Any: ...
    async def resource_update_drivers_group(self, *args: Any, **params: Any) -> Any: ...
    async def resource_update_trailer(self, *args: Any, **params: Any) -> Any: ...
    async def resource_upload_trailer_image(self, *args: Any, **params: Any) -> Any: ...
    async def resource_bind_unit_trailer(self, *args: Any, **params: Any) -> Any: ...
    async def resource_update_trailer_units(self, *args: Any, **params: Any) -> Any: ...
    async def resource_get_trailer_bindings(self, *args: Any, **params: Any) -> Any: ...
    async def resource_get_unit_trailers(self, *args: Any, **params: Any) -> Any: ...
    async def resource_cleanup_trailer_interval(self, *args: Any, **params: Any) -> Any: ...
    async def resource_update_trailers_group(self, *args: Any, **params: Any) -> Any: ...
    async def resource_update_tag(self, *args: Any, **params: Any) -> Any: ...
    async def resource_upload_tag_image(self, *args: Any, **params: Any) -> Any: ...
    async def resource_bind_unit_tag(self, *args: Any, **params: Any) -> Any: ...
    async def resource_update_tag_units(self, *args: Any, **params: Any) -> Any: ...
    async def resource_update_tag_message(self, *args: Any, **params: Any) -> Any: ...
    async def resource_get_tag_bindings(self, *args: Any, **params: Any) -> Any: ...
    async def resource_update_tags_group(self, *args: Any, **params: Any) -> Any: ...
    async def resource_update_email_template(self, *args: Any, **params: Any) -> Any: ...
    async def resource_get_orders_notification(self, *args: Any, **params: Any) -> Any: ...
    async def resource_update_orders_notification(self, *args: Any, **params: Any) -> Any: ...

    """
    References to account service
    https://sdk.wialon.com/wiki/en/sidebar/remoteapi/apiref/account/account
    """
    async def account_create_account(self, *args: Any, **params: Any) -> Any: ...
    async def account_delete_account(self, *args: Any, **params: Any) -> Any: ...
    async def account_get_account_data(self, *args: Any, **params: Any) -> Any: ...
    async def account_enable_account(self, *args: Any, **params: Any) -> Any: ...
    async def account_get_billing_plans(self, *args: Any, **params: Any) -> Any: ...
    async def account_list_change_accounts(self, *args: Any, **params: Any) -> Any: ...
    async def account_update_billing_plan(self, *args: Any, **params: Any) -> Any: ...
    async def account_update_plan(self, *args: Any, **params: Any) -> Any: ...
    async def account_update_sub_plans(self, *args: Any, **params: Any) -> Any: ...
    async def account_update_dealer_rights(self, *args: Any, **params: Any) -> Any: ...
    async def account_update_billing_service(self, *args: Any, **params: Any) -> Any: ...
    async def account_update_flags(self, *args: Any, **params: Any) -> Any: ...
    async def account_do_payment(self, *args: Any, **params: Any) -> Any: ...
    async def account_update_min_days(self, *args: Any, **params: Any) -> Any: ...
    async def account_get_account_history(self, *args: Any, **params: Any) -> Any: ...
    async def account_update_history_period(self, *args: Any, **params: Any) -> Any: ...
    async def account_change_account(self, *args: Any, **params: Any) -> Any: ...
    async def account_trash(self, *args: Any, **params: Any) -> Any: ...

    """
    References to unit service
    https://sdk.wialon.com/wiki/en/sidebar/remoteapi/apiref/unit/unit
    """
    async def unit_add_video_packets(self, *args: Any, **params: Any) -> Any: ...
    async def unit_update_video_status(self, *args: Any, **params: Any) -> Any: ...
    async def unit_update_command_definition(self, *args: Any, **params: Any) -> Any: ...
    async def unit_exec_cmd(self, *args: Any, **params: Any) -> Any: ...
    async def unit_get_command_definition_data(self, *args: Any, **params: Any) -> Any: ...
    async def unit_update_calc_flags(self, *args: Any, **params: Any) -> Any: ...
    async def unit_update_eh_counter(self, *args: Any, **params: Any) -> Any: ...
    async def unit_update_traffic_counter(self, *args: Any, **params: Any) -> Any: ...
    async def unit_update_mileage_counter(self, *args: Any, **params: Any) -> Any: ...
    async def unit_update_device_type(self, *args: Any, **params: Any) -> Any: ...
    async def unit_update_image(self, *args: Any, **params: Any) -> Any: ...
    async def unit_get_fuel_settings(self, *args: Any, **params: Any) -> Any: ...
    async def unit_update_fuel_rates_params(self, *args: Any, **params: Any) -> Any: ...
    async def unit_update_fuel_math_params(self, *args: Any, **params: Any) -> Any: ...
    async def unit_update_fuel_level_params(self, *args: Any, **params: Any) -> Any:
        # Deprecated
        ...
    async def unit_update_fuel_impulse_params(self, *args: Any, **params: Any) -> Any:
        # Deprecated
        ...
    async def unit_update_fuel_calc_types(self, *args: Any, **params: Any) -> Any:
        # Deprecated
        ...
    async def unit_get_accelerometers_calibration(self, *args: Any, **params: Any) -> Any:
        # Deprecated
        ...
    async def unit_get_report_settings(self, *args: Any, **params: Any) -> Any: ...
    async def unit_get_messages_filter(self, *args: Any, **params: Any) -> Any: ...
    async def unit_get_drive_rank_settings(self, *args: Any, **params: Any) -> Any: ...
    async def unit_get_trips(self, *args: Any, **params: Any) -> Any: ...
    async def unit_get_video_settings(self, *args: Any, **params: Any) -> Any: ...
    async def unit_get_vin_info(self, *args: Any, **params: Any) -> Any: ...
    async def unit_update_hw_params(self, *args: Any, **params: Any) -> Any: ...
    async def unit_update_phone(self, *args: Any, **params: Any) -> Any: ...
    async def unit_registry_custom_event(self, *args: Any, **params: Any) -> Any: ...
    async def unit_registry_fuel_filling_event(self, *args: Any, **params: Any) -> Any: ...
    async def unit_registry_maintenance_event(self, *args: Any, **params: Any) -> Any: ...
    async def unit_registry_status_event(self, *args: Any, **params: Any) -> Any: ...
    async def unit_update_phone2(self, *args: Any, **params: Any) -> Any: ...
    async def unit_update_unique_id2(self, *args: Any, **params: Any) -> Any: ...
    async def unit_update_sensor(self, *args: Any, **params: Any) -> Any: ...
    async def unit_calc_sensors(self, *args: Any, **params: Any) -> Any: ...
    async def unit_calc_last_message(self, *args: Any, **params: Any) -> Any: ...
    async def unit_update_service_interval(self, *args: Any, **params: Any) -> Any: ...
    async def unit_update_video_autopay(self, *args: Any, **params: Any) -> Any: ...
    async def unit_update_activity_settings(self, *args: Any, **params: Any) -> Any: ...
    async def unit_get_trip_detector(self, *args: Any, **params: Any) -> Any: ...
    async def unit_update_access_password(self, *args: Any, **params: Any) -> Any: ...
    async def unit_set_active(self, *args: Any, **params: Any) -> Any: ...
    async def unit_update_accelerometers_calibration(self, *args: Any, **params: Any) -> Any:
        # Deprecated
        ...
    async def unit_update_drive_rank_settings(self, *args: Any, **params: Any) -> Any: ...
    async def unit_update_report_settings(self, *args: Any, **params: Any) -> Any: ...
    async def unit_update_messages_filter(self, *args: Any, **params: Any) -> Any: ...
    async def unit_update_trip_detector(self, *args: Any, **params: Any) -> Any: ...
    async def unit_update_video_settings(self, *args: Any, **params: Any) -> Any: ...
    async def unit_upload_image(self, *args: Any, **params: Any) -> Any: ...

    """
    References to unit_group service
    https://sdk.wialon.com/wiki/en/sidebar/remoteapi/apiref/unit_group/unit_group
    """
    async def unit_group_update_units(self, **params: Unpack[unit_group.UnitGroupUpdateUnitsParams]) -> unit_group.UnitGroupUpdateUnitsResponse: ...

    """
    References to retranslator service
    https://sdk.wialon.com/wiki/en/sidebar/remoteapi/apiref/retranslator/retranslator
    """
    async def retranslator_update_units(self, **params: Unpack[retranslator.RetranslatorUpdateUnitsParams]) -> retranslator.RetranslatorUpdateUnitsResponse: ...
    async def retranslator_update_operating(self, **params: Unpack[retranslator.RetranslatorUpdateOperatingParams]) -> retranslator.RetranslatorUpdateOperatingResponse: ...
    async def retranslator_get_stats(self, **params: Unpack[retranslator.RetranslatorGetStatsParams]) -> retranslator.RetranslatorGetStatsResponse: ...
    async def retranslator_update_config(self, **params: Unpack[retranslator.RetranslatorUpdateConfigParams]) -> retranslator.RetranslatorUpdateConfigResponse: ...

    """
    References to route service
    https://sdk.wialon.com/wiki/en/sidebar/remoteapi/apiref/route/route
    """
    async def route_route_update_round(self, *args: Any, **params: Any) -> Any: ...
    async def route_get_round_data(self, *args: Any, **params: Any) -> Any: ...
    async def route_get_all_rounds(self, *args: Any, **params: Any) -> Any: ...
    async def route_get_schedule_time(self, *args: Any, **params: Any) -> Any: ...
    async def route_load_rounds(self, *args: Any, **params: Any) -> Any: ...
    async def route_update_config(self, *args: Any, **params: Any) -> Any: ...
    async def route_update_checkpoints(self, *args: Any, **params: Any) -> Any: ...
    async def route_update_schedule(self, *args: Any, **params: Any) -> Any: ...
    async def route_optimize(self, *args: Any, **params: Any) -> Any: ...

    """
    References to messages service
    https://sdk.wialon.com/wiki/en/sidebar/remoteapi/apiref/messages/messages
    """
    async def messages_unload(self) -> messages.MessagesUnloadResponse: ...
    async def messages_delete_message(self, **params: Unpack[messages.MessagesDeleteMessageParams]) -> messages.MessagesDeleteMessageResponse: ...
    async def messages_get_messages(self, **params: Unpack[messages.MessagesGetMessagesParams]) -> messages.MessagesGetMessagesResponse: ...
    async def messages_get_message_file(self, **params: Unpack[messages.MessagesGetMessageFileParams]) -> messages.MessagesGetMessageFileResponse: ...
    async def messages_get_packed_messages(self, **params: Unpack[messages.MessagesGetPackedMessagesParams]) -> messages.MessagesGetPackedMessagesResponse: ...
    async def messages_load_last(self, **params: Unpack[messages.MessagesLoadLastParams]) -> messages.MessagesLoadLastResponse: ...
    async def messages_load_interval(self, **params: Unpack[messages.MessagesLoadIntervalParams]) -> messages.MessagesLoadIntervalResponse: ...

    """
    References to report service
    https://sdk.wialon.com/wiki/en/sidebar/remoteapi/apiref/report/report
    """
    async def report_cleanup_result(self, *args: Any, **params: Any) -> Any: ...
    async def report_exec_report(self, *args: Any, **params: Any) -> Any: ...
    async def report_export_result(self, *args: Any, **params: Any) -> Any: ...
    async def report_get_result_chart(self, *args: Any, **params: Any) -> Any: ...
    async def report_render_json(self, *args: Any, **params: Any) -> Any: ...
    async def report_hittest_chart(self, *args: Any, **params: Any) -> Any: ...
    async def report_get_report_tables(self, *args: Any, **params: Any) -> Any: ...
    async def report_get_result_map(self, *args: Any, **params: Any) -> Any: ...
    async def report_get_result_subrows(self, *args: Any, **params: Any) -> Any: ...
    async def report_get_result_photo(self, *args: Any, **params: Any) -> Any: ...
    async def report_get_report_status(self, *args: Any, **params: Any) -> Any: ...
    async def report_select_result_rows(self, *args: Any, **params: Any) -> Any: ...
    async def report_get_result_rows(self, *args: Any, **params: Any) -> Any: ...
    async def report_get_report_data(self, *args: Any, **params: Any) -> Any: ...
    async def report_get_result_video(self, *args: Any, **params: Any) -> Any: ...
    async def report_update_report(self, *args: Any, **params: Any) -> Any: ...

    """
    References to exchange service
    https://sdk.wialon.com/wiki/en/sidebar/remoteapi/apiref/exchange/exchange
    """
    async def exchange_export_zones(self, *args: Any, **params: Any) -> Any: ...
    async def exchange_export_messages(self, *args: Any, **params: Any) -> Any: ...
    async def exchange_export_json(self, *args: Any, **params: Any) -> Any: ...
    async def exchange_import_json(self, *args: Any, **params: Any) -> Any: ...
    async def exchange_import_zones_save(self, *args: Any, **params: Any) -> Any: ...
    async def exchange_import_messages(self, *args: Any, **params: Any) -> Any: ...
    async def exchange_import_pois_save(self, *args: Any, **params: Any) -> Any: ...
    async def exchange_import_zones_read(self, *args: Any, **params: Any) -> Any: ...
    async def exchange_import_pois_read(self, *args: Any, **params: Any) -> Any: ...

    """
    References to render service
    https://sdk.wialon.com/wiki/en/sidebar/remoteapi/apiref/render/render
    """
    async def render_enable_layer(self, *args: Any, **params: Any) -> Any: ...
    async def render_create_poi_layer(self, *args: Any, **params: Any) -> Any: ...
    async def render_create_zones_layer(self, *args: Any, **params: Any) -> Any: ...
    async def render_create_messages_layer(self, *args: Any, **params: Any) -> Any: ...
    async def render_get_messages(self, *args: Any, **params: Any) -> Any: ...
    async def render_delete_message(self, *args: Any, **params: Any) -> Any: ...
    async def render_remove_layer(self, *args: Any, **params: Any) -> Any: ...
    async def render_remove_all_layers(self, *args: Any, **params: Any) -> Any: ...
    async def render_set_locale(self, *args: Any, **params: Any) -> Any: ...
    async def render_calculate_polygon(self, *args: Any, **params: Any) -> Any: ...
    async def render_calculate_polyline(self, *args: Any, **params: Any) -> Any: ...

    """
    References to token service
    https://sdk.wialon.com/wiki/en/sidebar/remoteapi/apiref/token/token
    """
    async def token_update(self, **params: Unpack[token_params.TokenUpdateParams]) -> token_params.TokenUpdateResponse  : ...
    async def token_list(self, **params: Unpack[token_params.TokenListParams]) -> token_params.TokenListResponse: ...
    async def token_login(self, **params: token_params.TokenLoginParams) -> token_params.TokenLoginResponse: ...

    """
    References to file service
    https://sdk.wialon.com/wiki/en/sidebar/remoteapi/apiref/file/file
    """
    async def file_list(self, *args: Any, **params: Any) -> Any: ...
    async def file_get(self, *args: Any, **params: Any) -> Any: ...
    async def file_put(self, *args: Any, **params: Any) -> Any: ...
    async def file_rm(self, *args: Any, **params: Any) -> Any: ...
    async def file_read(self, *args: Any, **params: Any) -> Any: ...
    async def file_write(self, *args: Any, **params: Any) -> Any: ...
    async def file_library(self, *args: Any, **params: Any) -> Any: ...
    async def file_mkdir(self, *args: Any, **params: Any) -> Any: ...
    async def file_type_library(self, *args: Any, **params: Any) -> Any: ...

    """
    References to events service
    https://sdk.wialon.com/wiki/en/sidebar/remoteapi/apiref/events/events
    """
    async def events_update_units(self, *args: Any, **params: Any) -> Any: ...
    async def events_check_updates(self, *args: Any, **params: Any) -> Any: ...
    async def events_load(self, *args: Any, **params: Any) -> Any: ...
    async def events_get(self, *args: Any, **params: Any) -> Any: ...
    async def events_unload(self, *args: Any, **params: Any) -> Any: ...

    """
    References to order service
    https://sdk.wialon.com/wiki/en/sidebar/remoteapi/apiref/order/order
    """
    async def order_update(self, *args: Any, **params: Any) -> Any: ...
    async def order_attach(self, *args: Any, **params: Any) -> Any: ...
    async def order_list_attachments(self, *args: Any, **params: Any) -> Any: ...
    async def order_detach(self, *args: Any, **params: Any) -> Any: ...
    async def order_get_attachment(self, *args: Any, **params: Any) -> Any: ...
    async def order_complete_from_history(self, *args: Any, **params: Any) -> Any: ...
    async def order_optimize(self, *args: Any, **params: Any) -> Any: ...
    async def order_route_update(self, *args: Any, **params: Any) -> Any: ...

    """
    References to requests service
    https://sdk.wialon.com/wiki/en/sidebar/remoteapi/apiref/requests/requests
    """

    async def apps_list(self, *args: Any, **params: Any) -> Any: ...
    # TODO:
